### ISSUE TITLE
Footnote tooltips are masked by the article list

### ISSUE THREAD

**Issue by chris-erickson** [feedbin/feedbin#106]
Open a tooltip on the left edge, and it'll be obscured by the article list.  I don't think floating over it is right, so it probably should shift right, and leave the arrow in the same position.

![screen shot 2014-06-11 at 10 30 08 am](https://cloud.githubusercontent.com/assets/3322287/3246710/e9aa3e24-f17d-11e3-8ea9-c75dd98852a9.png)

**Comment by benubois** [comment]
Thanks, this should be fixed now.
