### ISSUE TITLE
Select tag when adding a new feed

### ISSUE THREAD

**Issue by thejspr** [feedbin/feedbin#117]
Being able to select a tag from the "add feed" dialog would make it easier (for me) to add new sources to feedbin. I suggest we can reuse the existing tag selector somehow. If this is something the community could find useful, I'd be happy to implement it.

**Comment by leejoramo** [comment]
I would find this useful.

**Comment by NorrinRadd** [comment]
Very much needed.  I can't find feeds after they're added.  How can you tag them if they don't have a tag and aren't shown anywhere.... or Feedbin seems to be determining a tag to give it in some secret indeterministic fancy.....

**Comment by ldexterldesign** [comment]
+1

**Comment by thejspr** [comment]
Thanks @benubois  https://feedbin.com/blog/2017/03/22/subscribe-improvements/
