### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by lwis** [feedbin/feedbin#131]
Hi Folks,

I spent a bit of time over the weekend attempting to setup a [Docker](https://www.docker.com/) image for easier local deployments, I created a [repo](https://github.com/lwis/feedbin-docker), I'm having some issues deploying and getting the DB setup for the first time - I've included both Fedora and Ubuntu Dockerfiles and would appreciate your contributions in setting up!

Precursor: I'm not overly familiar with Ruby, but have a reasonable understanding - and want to learn.

**Comment by fnkr** [comment]
I have the same error, @lwis did you found out how to solve the error?

**Comment by lwis** [comment]
@fnkr this is where I got with it; https://github.com/lwis/feedbin-docker

After hours of trying I figured it's not built to be run standalone, many things don't work correctly.

**Comment by fnkr** [comment]
@lwis Have you found out what exactly was wrong? I installed Feedbin directly and did not use a Docker container.

**Comment by fnkr** [comment]
@lwis Thanks for your reply, have you found out what exactly was wrong? I installed Feedbin directly and did not use a Docker container.

**Comment by lwis** [comment]
@fnkr You need to drop before first creation, I believe. It was a few months ago since I last looked at this and I barely had it working so maybe @benubois can offer some support :)

**Comment by fnkr** [comment]
I opened a new issue for this. #136

**Comment by karllhughes** [comment]
Is anyone still interested in a Docker setup for running this project?

I'd really like to be able to use Docker to run my own instance of the feedbin suite (I'm running into limits with lots of feeds in the paid service), so I'm thinking of starting this effort back up.

If anyone would like, I'm happy to update you here on my progress.

**Comment by lwis** [comment]
@karllhughes absolutely!

**Comment by dewey** [comment]
Does anyone have any experience with the existing docker images already? Any recommended ones?

**Comment by romanar** [comment]
Try - https://github.com/scavone/feedbin-docker
However, I had no luck with this one.

**Comment by dewey** [comment]
Yea I saw that and the abandoned issue tracker so I figured I'd wait for some better suggestion 😀

**Comment by rocwhite123** [comment]
I've written a short description on how to self-host Feedbin with Docker [here](https://blog.xudd.tk/computer/feedbin). The write-up also uses OpenShift, but it's not necessary.

**Comment by fnkr** [comment]
@rocwhite123 Hi, thanks for your work! It would be nice to have the Dockerfile you used to build the image, could you please provide that Dockerfile?
