### ISSUE TITLE
Import without AWS?

### ISSUE THREAD

**Issue by jlnostr** [feedbin/feedbin#133]
Hey, 
I really like feedbin and get my own instance installed. But there is one thing, I personally don't like: the requirement of AWS. Here in Germany, this is a dealbreaker.

So it would be great to see feedbin working without the requirement of AWS. There was a issue (#5) for this option, but as I see in the code it had never been implemented. Would be nice to see it!

**Comment by benubois** [comment]
Hi @jlnostr,

Glad you like Feedbin!

I would accept a pull request to add local file uploads (as alternative to S3). However it's not something I'm interesting in implementing.

Thanks!

**Comment by wiwie** [comment]
As I can see there hasn't been any progress on this for a while.

In the meantime, please add the AWS requirement to the README.
I started installing feedbin believing, that it would be completely self-hosted.
