### ISSUE TITLE
Search result count

### ISSUE THREAD

**Issue by CasperTDK** [feedbin/feedbin#135]
Hi

I am sometimes using search + 'mark as read' to clean up my feed.
I have no idea if I am marking 10 or 500 entries as read. This is important to to as it can show that I've made a bad search (the count is very different from what I expected

I'd like either:
1) To see the search result count on the search page 
AND/OR 
2) Have the count added to the following dialog message:
https://github.com/feedbin/feedbin/blob/4e09db21a3ce859de2ccf48baa16fdb13f9f8b3d/app/views/shared/_entries.js.erb#L63

Thank you!

**Comment by benubois** [comment]
Great idea! Thanks!
