### ISSUE TITLE
Shift-V opens page in foreground (Chrome)

### ISSUE THREAD

**Issue by jridgewell** [feedbin/feedbin#142]
Using `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36`, seems to have started in the last week.

**Comment by benubois** [comment]
Hi @jridgewell,

Unfortunately Google has changed this behavior. 

As a workaround I made an [extension](https://chrome.google.com/webstore/detail/feedbin-link-opener/naflkhnfmneiigdcphekaemdmeajiand).

There's a bit [more about this on the blog](http://blog.feedbin.com/2015/03/09/link-opener-for-chrome/) too. 

Thanks!

**Comment by jridgewell** [comment]
That's a shame. Thanks!
