### ISSUE TITLE
Add tag_id search operator

### ISSUE THREAD

**Issue by joewiz** [feedbin/feedbin#143]
The [search syntax](http://help.feedbin.com/search-syntax/) allows search by feed (by use of the `feed_id` operator) but not by tag.  I use tags pretty extensively and would like a way to search within these.  Please consider adding tag_id to the search syntax.  

A typical search for me would be to search for unstarred, unread articles within the Apple tag (whose id is 88, as shown when I hover over the tag name with my mouse and see the URL, https://feedbin.com/tags/88):

  `is:unread is:unstarred tag_id:88`

Thanks for considering this request!

**Comment by benubois** [comment]
Great idea! This is now available using `tag_id:123`.

**Comment by joewiz** [comment]
It's working beautifully.  Thank you so much, Ben, for implementing this and doing so so quickly!

**Comment by robwco** [comment]
How do you find a tag id?

**Comment by joewiz** [comment]
In the web app, hover over a tag, and the browser should show you the associated URL, e.g.:

> ![screen shot 2017-02-21 at 1 15 16 am](https://cloud.githubusercontent.com/assets/59118/23152903/3f891924-f7d3-11e6-96de-71fb5dac9e77.png)

Here the tag "Asia" corresponds to tag_id `5047`.

**Comment by robwco** [comment]
Thank you!
