### ISSUE TITLE
feeds.subscriptions_count = 1 (feed_refresher_scheduler)

### ISSUE THREAD

**Issue by fnkr** [feedbin/feedbin#144]
Shouldn't it be `>= 1` or `> 0` instead of `> 1`?

https://github.com/feedbin/feedbin/blob/882cf59/app/workers/feed_refresher_scheduler.rb#L17

**Comment by benubois** [comment]
Looks right to me. The intent is that a full refresh is done every other time so feeds with more subscribers are refreshed twice as much.
