### ISSUE TITLE
Share menu icon is missing

### ISSUE THREAD

**Issue by iwehrman** [feedbin/feedbin#150]
This happens to me on different computers and on both Chrome and Safari:

![closed](https://s3.amazonaws.com/f.cl.ly/items/2a2W1i163W1K3o272Z0z/Image%202015-06-19%20at%207.39.26%20AM.png)
![open](https://s3.amazonaws.com/f.cl.ly/items/181B3f343M2O0Z0f2X3w/Image%202015-06-19%20at%207.39.49%20AM.png)

Note the missing "share" menu icon. I believe the relevant error is:

```
https://camo-feedbin.herokuapp.com/c759bc94764ab3fc52369e7b72b876aea381122d/687474703a2f2f7069322e6665656473706f7274616c2e636f6d2f722f3233313036343135363835302f752f34392f662f3634383332362f632f33353037302f732f34373163643764322f73632f32382f613274322e696d67
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) 
```

My feedbin account name is the same as my Github account name.

**Comment by benubois** [comment]
Hi @iwehrman,

Sorry for the icon trouble! Unfortunately I'm not able to reproduce this yet.

Would you mind checking out the source in your browser's developer tools and taking a screenshot? It could also be useful to get the full source of the page.

For me it looks like this:

![screen shot 2015-06-19 at 12 45 53 pm](https://cloud.githubusercontent.com/assets/133809/8261685/4783fdb8-1681-11e5-906e-1b825935b7dc.png)

The 404 error is unrelated. `camo-feedbin.herokuapp.com` is the TLS enabled image proxy that feed images are passed through.

**Comment by iwehrman** [comment]
Bah! I just realized that [my adblocker uBlock](https://www.ublock.org/) is the culprit here. A thousand pardons. Love the app and the service! Carry on!

**Comment by benubois** [comment]
No problem :smiley:  Thanks for the update.
