### ISSUE TITLE
Mac Install: Feedbin.dev not coming up

### ISSUE THREAD

**Issue by chrisbrinkworth** [feedbin/feedbin#151]
I've followed the [Mac installation instructions](https://github.com/feedbin/feedbin/blob/master/doc/INSTALL-mac.md) but I can't seem to bring up Feedbin.dev. I'm so close!

My server/localhost automatically redirects http to https. Could this be the issue? I looked into installing powssl but it appears to be outdated.

Anyway, I'm getting ahead of myself. Please assist if you've installed on a Mac server lately.

Thank you!

Here are the detailed steps I took to install so far (with amendments for the issues I've encountered):

Command Line Tools
Downloaded and installed

Homebrew
> ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

rbenv
> brew update
> brew install rbenv

Added: 
> export RBENV_ROOT=/usr/local/var/rbenv

> brew install ruby-build
> echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
> source ~/.bash_profile

Ruby 2.1.4
> rbenv install 2.1.4
> rbenv global 2.1.4

Bundler
> gem install bundler

Postgres 9.2.4
> brew install caskroom/cask/brew-cask
> brew cask install postgres
> open ~/Applications/Postgres.app

Redis 2.6.14
> brew update
> brew install redis
> redis-server 

Instead of this, can use the following to load on startup as well as run now with launchctl
> ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
> launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist

ImageMagick (requirement for rmagick gem)
> brew update
> brew install ImageMagick
--Make sure to follow post install instructions. I believe this is referring to any commands above, not just ImageMagick, and probably especially ImageMagick as there don’t appear to be any post steps for that install

Clone Feedbin
> git clone https://github.com/feedbin/feedbin.git cd feedbinIf you haven’t already, run:
> rbenv rehash 
so rbenv can “see” the brew installed ruby 2.1.4 instead of the 1.9.3. If you don’t you’ll get the error "Your Ruby version is 1.9.3, but your Gemfile specified 2.1.4" bundle

If you receive an error during “bundle”

Error:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    /usr/local/var/rbenv/versions/2.1.4/bin/ruby extconf.rb
checking for pg_config... yes
Using config values from /Applications/Server.app/Contents/ServerRoot/usr/bin/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/var/rbenv/versions/2.1.4/bin/ruby
    --with-pg
    --without-pg
    --enable-windows-cross
    --disable-windows-cross
    --with-pg-config
    --without-pg-config
    --with-pg_config
    --without-pg_config
    --with-pg-dir
    --without-pg-dir
    --with-pg-include
    --without-pg-include=${pg-dir}/include
    --with-pg-lib
    --without-pg-lib=${pg-dir}/lib

extconf failed, exit code 1

Gem files will remain installed in /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/pg-0.18.2 for inspection.
Results logged to /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/pg-0.18.2/gem_make.out
An error occurred while installing pg (0.18.2), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.2'` succeeds before bundling.

Solution was to point pg_config to the brew installed PostgreSQL install instead of the Server.app one:
> env ARCHFLAGS="-arch x86_64" gem install pg -- \ > --with-pg-config=/Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config to prepend the environment architecture flags
and
> export ARCHFLAGS="-arch x86_64” to put it in the bash profile

Use this command to find the location if the version changes:
sudo find / -name "pg_config"

Setup the database (Make sure you're running Postgres and Redis): running
>rake db:setup

A warning during this step:
“WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.0"

Solution was to ignore.
Start scheduled tasks and background workers
> bundle exec foreman start

pow
> curl get.pow.cx | sh
> ln -nfs /mypath/yesIputtherealone/feedbin ~/.pow/feedbin
At this point you should be able to load feedbin.dev in your browser.

**Comment by benubois** [comment]
Sounds like the issue is with installing `pg` so I'd recommend looking at how to install pg.
