### ISSUE TITLE
How to configure nginx with routes ?

### ISSUE THREAD

**Issue by unixfox** [feedbin/feedbin#159]
I want to use the api of Feedbin self-hosted but I'm using proxy_pass to communicate with the ruby application but I can't setup a sub domain for the api, it doesn't work.

How to configure nginx with ruby routes ?

**Comment by unixfox** [comment]
Does the official website of Feedbin use Passenger ?

**Comment by benubois** [comment]
Hi, sorry I cannot help with environment specific questions.
