### ISSUE TITLE
Elasticsearch version

### ISSUE THREAD

**Issue by fnkr** [feedbin/feedbin#168]
Hi,

does Feedbin still rely on Elasticsearch <1.0? I would like to update my Feedbin & Elasticsearch instance.

**Comment by benubois** [comment]
Yup! Elasticsearch > 1.0 has breaking changes that I have not addressed, mostly around [percolators](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-percolate.html). If you don't use actions it might still work with a newer version.
