### ISSUE TITLE
Refresher Sits Idle

### ISSUE THREAD

**Issue by travisghansen** [feedbin/feedbin#169]
I've just updated my self-hosted install from ~May 2015 to latest master of both feedbin and refresher.

After updating I noticed my feeds were no longer being updated and so spent some time investigating.  I'm not a ruby dev but I bisected the code and found the culprit to be commit db3301f6f52c3715f1abce656a226064bbc47d4f

Do you see anything in there that would introduce issue to a self-hosted environment?

**Comment by benubois** [comment]
Ah, yeah, looks like you'll need to update your database to add feed_types. Running this in the project root should work:

```bash
bundle exec rails runner "Feed.update_all(feed_type: Feed.feed_types[:xml])"
```

**Comment by travisghansen** [comment]
I originally ran ```rake db:migrate``` should that be I migration or no?

I'll test out your solution regardless.

**Comment by travisghansen** [comment]
That appears to have worked.  Thanks for the info!

**Comment by benubois** [comment]
@travisghansen great!

> I originally ran rake db:migrate should that be a migration or no?

This probably should have been a migration, however in production it's tricky to add a new column with a default without locking the database.
