### ISSUE TITLE
No feed found

### ISSUE THREAD

**Issue by chris25640** [feedbin/feedbin#170]
Hi, Thank you for your work,

I followed the instructions in github but i have a problem, I have an error for all the feeds I want to add : 

"Feed not found"

I have try a lot of url, it's always the same problem, what i have forget?

I have install it on Fedora 23 Server, no problem for install and no problem for create a account, i just can't add feeds :(

Thanks,

PS: Sorry for my bad english

**Comment by fnkr** [comment]
Which Elasticsearch version are you using? Feedbin requires elasticsearch < 1.0, e.g. 0.90.1.
