### ISSUE TITLE
Idea: tell user when a feed seems to be dead

### ISSUE THREAD

**Issue by maxjacobson** [feedbin/feedbin#172]
Hello!

I was doing a little re-organizing of the labels for my feeds and realized that one of them hadn't been updated in multiple years.

I looked a little bit in the feedbin code for where the request is made and found this bit: https://github.com/feedbin/refresher/blob/219657026ebfd3b21cfb18c99c43476a246cbda5/app/models/fetched.rb#L22-L40

If I'm understanding it right, unparseable feeds are treated as empty feeds.

The reason I like to use feedbin is to help keep track of things. For me, I would appreciate knowing if a feed has stopped delivering information, so I can see if it was renamed or moved and then continue to keep track of it.

I'm not sure if it makes sense to tell them right away... maybe there's some momentary downtime for a blog, but it's not truly dead.

What do you think?

**Comment by ldexterldesign** [comment]
+1
