### ISSUE TITLE
Add keyboard shortcut for "Toggle width"

### ISSUE THREAD

**Issue by Erikmitk** [feedbin/feedbin#174]
I find myself frequently switching between the width settings. Narrow for articles/newsletters, wide for webcomics. A shortcut would make changing the setting easier and remove the back and forth with the mouse.

**Comment by ncFoCo** [comment]
Does full screen view work for comics (shift-F)?

**Comment by Erikmitk** [comment]
Full Screen doesn’t change the width of the content column. So with Full Screen the image size stays the same, but I don’t see the feed list. But what I want is to increase the width and therefore the size of the image.

See the screenshot.
![bugmartini_comic_full_width](https://cloud.githubusercontent.com/assets/180686/14639836/ecd28fca-063e-11e6-80bd-44b91bea818f.png)

**Comment by ncFoCo** [comment]
Thanks. I see what you are saying now. The image width is definitely not ideal.  
  
Removing ```max-width: 100%``` on the ```img``` tag helps increase the size, but the page centering is off. I wonder if the CSS in full screen mode can be optimized to increase image size?

**Comment by Erikmitk** [comment]
I don’t think a CSS solution would work well in that case, since the markup of the content is determined by the feed itself. You never know what edge cases you encounter and the only thing to adjust is the content column itself. The reading experience in full-screen is very well and adjusting the column width there would lessen the experience in my opinion.

Webcomics are an outlier I guess, because they are distributed as images and not as text and therefore require more space sometimes. I’d be totally fine if I could change the width in those cases manually (which I can now with the mouse). Maybe remembering the setting on a per feed basis would be an additional idea.
