### ISSUE TITLE
New Feature request: Play video from https://asciinema.org within feedbin

### ISSUE THREAD

**Issue by molstrangler** [feedbin/feedbin#183]
Hi,

Right now when I click on a asciinema video FeedBin launches their website and the video is played.  I would like to play the video embedded in the feedbin article just like youtube & vimeo.

**Comment by molstrangler** [comment]
https://asciinema.org/docs/embedding

**Comment by benubois** [comment]
Hi, 

Unfortunately this player uses JavaScript (rather than an iFrame like Vimeo and YouTube) so it cannot be supported at this time due to security and performance issues with loading 3rd party JavaScript.
