### ISSUE TITLE
"Subscribe with Feedbin" bookmarklet

### ISSUE THREAD

**Issue by alexkrolick** [feedbin/feedbin#190]
It would be cool if there was as way to quickly subscribe to a feed using a bookmarklet.

**Comment by benubois** [comment]
Hi @alexkrolick,

[This](https://gist.github.com/benubois/4c1f9203d522854ffc78f0ca2aa3ce0f) should work. Try saving bookmarklet.html locally and open it in your browser. Then drag the link to your bookmark bar.

Also if you're using Chrome there's a [handy extension](https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd?hl=en) that can be configured to work with Feedbin. Use the URL `https://feedbin.com?subscribe=%s` in the config.

Thanks!
