### ISSUE TITLE
Feature request: Rename feeds

### ISSUE THREAD

**Issue by johnbillion** [feedbin/feedbin#193]
Several feeds that I subscribe to don't have very descriptive names, especially feeds for things such as forum threads.

The ability to rename a feed would be great.

**Comment by DavidOliver** [comment]
You can double-click the feed name to rename it.

**Comment by johnbillion** [comment]
@DavidOliver Thanks!

**Comment by brendanlong** [comment]
I wonder if this feature should be made more obvious. I've been using Feedbin since the beginning and had no idea..

**Comment by DavidOliver** [comment]
[We can also use the feed name in the toolbar to rename now](https://feedbin.com/blog/).

@brendanlong, my opinion on this is that a pencil icon against each feed name would be overkill for a feature that will be used infrequently relative to reading sessions. However, an indication in the feed toolbar could well be justified.

**Comment by OJFord** [comment]
> a pencil icon against each feed name would be overkill for a feature that will be used infrequently relative to reading sessions

It could appear only on hover, I've seen that elsewhere and I think it's quite effective.

**Comment by benubois** [comment]
I'm good with no icon for now. Renaming feeds is a nice to have, but not a requirement for using Feedbin, so I don't think this needs to be super explicit. For the people that cannot figure out how to rename feeds, the top three Google results get you the answer.

![screen shot 2017-03-22 at 7 38 59 am](https://cloud.githubusercontent.com/assets/133809/24203499/24a8f48c-0ed3-11e7-8279-642acd77503e.png)
