### ISSUE TITLE
Replace Readability with Mercury

### ISSUE THREAD

**Issue by iwehrman** [feedbin/feedbin#197]
The Readability parser API will be/has been shut down as of December 10, 2016: 

https://medium.com/@readability/the-readability-bookmarking-service-will-shut-down-on-september-30-2016-1641cc18e02b#.r15njwb72

In its place, the Mercury Toolkit is recommended:
https://mercury.postlight.com/

The Readability button in the Feedbin UI is currently broken. If enabled, the post spins indefinitely with empty content, and clicking the button does not disable the mode.

**Comment by benubois** [comment]
Done!
