### ISSUE TITLE
Keyboard shortcuts `j` and `k` not scrolling up and down through articles in full screen

### ISSUE THREAD

**Issue by ncFoCo** [feedbin/feedbin#199]
I am getting used to navigating through my feeds using `h`, `j`, `k`, and `l`.  

The behavior observed in the main feed view (as expected):  
- Navigate between columns using `h` and `l` in the main feed view.  
- Navigate rightward to an article using `l`.  
- Scroll up and down in the article with `j` and `k`.  

The behavior observed in full-screen article view (reproducible):  
- Open an article in full-screen using `Shift+f`.  
- Try to use `j` and `k` to scroll through the article.  
- Feedbin jumps between articles instead of scrolling up and down through the article.  
- I have tried ensuring that I am positioned as far to the right before opening the full-screen view and `j` and `k` still navigate between articles.  

Thanks for your time.  

``` text  
OS: Windows 7 Professional SP1
Browser: Version 55.0.2883.87 m (64-bit)  
```

**Comment by OJFord** [comment]
Unfortunately, I think this is intended: http://help.feedbin.com/keyboard-shortcuts/

Page up/down does sort of what we want (<kbd>Fn</kbd>-<kbd>[up]</kbd> on a Mac keyboard without <kbd>PgUp</kbd> key, not sure about others) but with more of a jump of course.

**Comment by Zegnat** [comment]
Note that you can always use <kbd>space</kbd> to scroll through the article, just like how it works on any website. The help page describes its use as “Navigate through unread items”, but it will scroll whatever the current item is and only jump to the next if you hit <kbd>space</kbd> space again after reaching the bottom of the article.

That is how I scroll through articles and keep <kbd>j</kbd> reserved for instantly jumping to the next.
