### ISSUE TITLE
Whitespace broken in 'full content load' of pre tags

### ISSUE THREAD

**Issue by OJFord** [feedbin/feedbin#203]
In 'full content load' of a feed item with something (e.g. a `code snippet`) in `<pre></pre>` tags, the usual pre-formatted whitespacing rules are lost, and it's rendered like prose.

For example (PEP 542, latest in [this feed](https://www.python.org/dev/peps/peps.rss/)):
```html
<pre class="literal-block">class MyClass:
    ...

my_instance = MyClass()

def my_function(self):
    ...

# Assign to class attribute
MyClass.my_function = my_function

# Or assign to instance attribtue
my_instance.my_function = my_function
</pre>
```
becomes:
![screen shot 2017-02-28 at 00 34 51](https://cloud.githubusercontent.com/assets/3946014/23386377/f1e075b6-fd4d-11e6-9c08-2e04838090ee.png)

**Comment by benubois** [comment]
Hi @OJFord,

Feedbin uses [Mercury Parser](https://mercury.postlight.com/web-parser/) to power this feature. It looks like Mercury strips out some of the newlines.

For instance here's the difference between the original HTML vs Mercury:

```html
Original
<pre class="literal-block">\nclass MyClass:\n    ...\n\nmy_instance = MyClass()\n\ndef my_function(self):\n    ...\n\n# Assign to class attribute\nMyClass.my_function = my_function\n\n# Or assign to instance attribtue\nmy_instance.my_function = my_function\n</pre>

Mercury
<pre class="literal-block">\nclass MyClass: ... my_instance = MyClass() def my_function(self): ... # Assign to class attribute\nMyClass.my_function = my_function # Or assign to instance attribtue\nmy_instance.my_function = my_function\n</pre>
```

Not sure why Mercury preserves some of the newlines. Unfortunately there's nothing I can do on Feedbin's side to fix this.

**Comment by OJFord** [comment]
Thanks for looking into it so quickly.

I've reported this to Mercury folks via email, so hopefully it can be fixed up there and be auto-magically fixed in feedbin. :slightly_smiling_face:
