### ISSUE TITLE
Keyboard shortcuts don't work after pressing 'a' and then escape

### ISSUE THREAD

**Issue by ksuther** [feedbin/feedbin#207]
Keyboard shortcuts stop working in the following situation:

- Press 'a' to add a new feed
- Press escape to close the new feed field
- Try to use any keyboard shortcut
- Keyboard shortcuts don't work until you click in the window again

I found this when trying to press 'a' to mark everything as read and had the new feed field appear, then ended up stuck until I clicked in the window again.

**Comment by benubois** [comment]
Hi @ksuther,

Thanks for reporting this!

I believe it should be fixed now.
