### ISSUE TITLE
force_ssl from ENV

### ISSUE THREAD

**Issue by travisghansen** [feedbin/feedbin#215]
Any chance you can add something like this to `config/environments/production.rb`?
```
  config.force_ssl = true
  if ENV["FORCE_SSL"] == 'false'
    config.force_ssl = false
  end
```
Trying to dockerize things and that would help.
Thanks!

**Comment by PonderingGrower** [comment]
I'm also working on dockerizing feedbin and this is one of the things getting in my way. I want to limit custom changes to feedbin code to a minimum.
