### ISSUE TITLE
sample production nginx configuration

### ISSUE THREAD

**Issue by travisghansen** [feedbin/feedbin#217]
Is there a sample file around that you're using to show what options/etc are enabled for nginx?  I've got a working version serving up static assets and using proxy pass appropriately just interested in what nuanced options may be helpful.

Thanks!

**Comment by benubois** [comment]
Hi @travisghansen,

[This guide](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-unicorn-and-nginx-on-ubuntu-14-04) has info for how to deploy rails + nginx. Should work great for Feedbin.

**Comment by travisghansen** [comment]
@benubois thanks this helped quite a bit.  Not really a `ruby` guy so some of this stuff is pretty foreign.  As an FYI I've put together a number of images to run the full stack.  Additionally I have a `swarm` compatible compose file to use the images and scale as needed/wanted.  If you have any interest in reviewing or using let me know.

**Comment by travisghansen** [comment]
@benubois also, can you share what kind of setup you have for `X-Accel-foo`?  I seem to be getting some 500 errors due to my setup on that front `X-Accel-Mapping header missing`.  If I understand the setup correctly I either need to run nginx on the same host as feedbin *or* have some shared storage available to both.  In any case if you could hand off some pointers on this front it would be helpful.

Thanks!

**Comment by benubois** [comment]
Hi,

I’m not sure what that setting does and don’t have it configured for Feedbin. 

In general I cannot effectively offer support for getting Feedbin up and running, but since it is largely a vanilla rails app there are plenty of resources out there to get up to speed. 

Thanks!

**Comment by travisghansen** [comment]
@benubois sure, this one is more of details to the specific app but I hear ya.
