### ISSUE TITLE
migrating instances

### ISSUE THREAD

**Issue by travisghansen** [feedbin/feedbin#218]
I'm trying to migrate instances.  What else is critical besides `postgres` data?  I pulled that over and noticed clicking on the *All* link showed no history items even though I see them in the database.

Files?
Redis?
ES?

Thanks!

**Comment by travisghansen** [comment]
@benubois is there an invocation I can do to reload ES data from postgres?

What's the proper way to invoke `FaviconMigration` as I've noticed I have none of them showing up anymore?

**Comment by benubois** [comment]
All of it!

You can reindex the search server with:

```
SearchServerSetup.perform_async(nil, true, Entry.last.id)
```

The FaviconMigration (or anything in /app/jobs) can be run like this in the console:

```
FaviconMigration.perform_async(nil, true)
```
