### ISSUE TITLE
Feature request: keyboard shortcut to copy URL to clipboard

### ISSUE THREAD

**Issue by joeshaw** [feedbin/feedbin#221]
I often want to share articles I read with others, but not through the available sharing services.  The [clipboard web API](https://caniuse.com/#feat=clipboard) is now well-supported across all desktop browsers, and it'd be nice if Feedbin offered the ability to copy to the clipboard either through the sharing system or with its own dedicated shortcut key.

**Comment by benubois** [comment]
Good idea! This is now available by pressing `shift` `c`

Which sharing services are you missing? Are you familiar with the [custom sharing/read-it-later feature](https://feedbin.com/help/sharing-read-it-later-services/)?

![screen shot 2017-08-28 at 4 06 37 pm](https://user-images.githubusercontent.com/133809/29797331-5726ee0e-8c0b-11e7-9dab-1e4f209e7330.png)

**Comment by joeshaw** [comment]
Awesome! Thanks a lot.

It's not really a problem of lack of services.  It's typically for sending a link in a private chat like Slack or Hangouts.
