### ISSUE TITLE
Correctly formatted HTML tag stripped from headline

### ISSUE THREAD

**Issue by skddc** [feedbin/feedbin#232]
I just had a feed item with the RSS source containing `A free guide to &lt;head&gt; elements` as title look like this in the reader:

![screenshot from 2017-11-18 16-38-42](https://user-images.githubusercontent.com/842/32982073-f810e9f6-cc7e-11e7-9336-ad8d802eba9b.png)

**Comment by benubois** [comment]
Hi @skddc,

Could you provide a link to the feed?

Thanks!

**Comment by skddc** [comment]
Sure: https://5apps.com/news/stories/latest.rss

**Comment by benubois** [comment]
Thanks!

I believe the correct way to express this in RSS would be:

```xml
<title><![CDATA[A free guide to &lt;head&gt; elements]]></title>
```

However this feed neglects the `CDATA` so it's [indistinguishable from encoded HTML that should be displayed as HTML](https://cyber.harvard.edu/rss/encodingDescriptions.html).

```xml
<title>A free guide to &lt;head&gt; elements</title>
```

**Comment by skddc** [comment]
Oh ok, thanks. I thought it was different for title than for the body, so I'm glad I learned something today. :)
