### ISSUE TITLE
rake db:setup won't work with Postgres <9.6

### ISSUE THREAD

**Issue by phoenix1796** [feedbin/feedbin#238]
The structures.sql contains various parameters which only work with postgres 9.6 and above

**Comment by benubois** [comment]
Hi!,

Feedbin now only supports postgres 10. I've updated the readme to reflect this.

However, as far as I know there are no breaking changes yet, so you can safely edit the structure.sql to remove anything that's causing an error for you. Or upgrade to pg 10.

Thanks!
