### ISSUE TITLE
No support for more than on hash tag

### ISSUE THREAD

**Issue by molstrangler** [feedbin/feedbin#242]
I am unable to add a Twitter feed with more than one hashtag. I get the error "Feed not found".

**Comment by benubois** [comment]
Hi! 

No plans to add support for this directly in Feedbin. However I think this is easily achievable using Twitter search. If you go to Twitter and perform a search like: 

```
#NationalNappingDay OR #MondayMotivation
```

Then paste the [resulting URL](https://twitter.com/search?q=%23NationalNappingDay%20OR%20%23MondayMotivation&src=typd) into Feedbin, you then have a feed of tweets with any of the hashtags you searched for.

**Comment by molstrangler** [comment]
Hi,

I tried this and the feed is added but the feed does not appear.  When I go to my feed list it shows that I'm subscribed but shows:

```
LAST UPDATED
N/A
```
