### ISSUE TITLE
Drop hstore requirement

### ISSUE THREAD

**Issue by nanaya** [feedbin/feedbin#244]
I keep forgetting to install contrib (which contains `hstore` extension) when doing reinstalls which caused some grief.

I'm pretty sure `jsonb` (or `json`) covers everything needed from `hstore` so I just migrated those columns over.

Direct conversion doesn't work and I don't want to dig up if `change_column` has `USING` option to cast stuff so I just create migration with this for `up`:

```sql
execute <<-SQL
  ALTER TABLE "supported_sharing_services" ALTER COLUMN "settings" TYPE jsonb USING settings::jsonb;
  ALTER TABLE "users" ALTER COLUMN "settings" TYPE jsonb USING settings::jsonb;
SQL
```

My feedbin db user isn't superuser so I dropped the extension separately.

**Comment by benubois** [comment]
Hi!

I'm up for making this change. 

Could you create a pull request with a proper migration?

> I'm pretty sure jsonb (or json) covers everything needed from hstore so I just migrated those columns over.

Any way to be 100% sure?

Thanks!

**Comment by nanaya** [comment]
Well for starter, `AR::Store`, which is how those columns are currently used, supports both so I believe either are handled transparently. How it's handled after migration but before restart might be questionable though.

Additionally, [this post](https://www.citusdata.com/blog/2016/07/14/choosing-nosql-hstore-json-jsonb/) explains the difference better than I could ever do.

> Could you create a pull request with a proper migration?

Maybe if I have time to but it's not high on my priority list so it probably won't happen anytime soon.
(and I don't have dev env so I've been doing this all on my only personal instance and it's been diverged a bit)
