### ISSUE TITLE
Add PWA capabilities

### ISSUE THREAD

**Issue by maracuja-juice** [feedbin/feedbin#247]
It would be really nice if Feedbin is a PWA that can easily be added to the home screen and also be used offline (serviceWorker)

**Comment by OllyHodgson** [comment]
It appears this has now been implemented. I can add it to my iOS home screen and it appears without browser chrome. External links load in Safari. It's nearly replaced Reeder for me.

It would be nice if #278 were implemented so when switching back to the "app" it would remember where it was.

**Comment by caldenjacobs** [comment]
I'm not seeing Progressive Web App support on my end. This would be a wonderful feature to have—especially considering the dearth of Android apps with stable Feedbin sync built in

**Comment by serovar** [comment]
I opened an [issue](https://github.com/mozilla-mobile/fenix/issues/9897) for it on the Fenix (Firefox Preview for Android) GitHub, and they told me that the problem is the website doesn't count as a PWA without a web app manifest.

**Comment by oscarotero** [comment]
Yes, please 🙏 
Add support for PWA, it's really easy to implement and allows to install feedbin in the phone, like any other app. I've switched to feedbin some days ago and it's the only thing that I'm missing.

**Comment by serovar** [comment]
I wrote to them on [Twitter](https://twitter.com/feedbin/status/1262840464711077890), they said that they will look into it, finger crossed :)

**Comment by benubois** [comment]
A manifest has been added so Feedbin should be installable on more platforms now.

Offline support would be a much larger project and isn't currently planned.
