### ISSUE TITLE
Tweets in the article pane may be cut off when the window is very wide

### ISSUE THREAD

**Issue by dotHTM** [feedbin/feedbin#249]
The Left side of the article view is cut off for tweet items when viewed with a wide window.

The effect disappears (displaying properly) when at a sufficient narrowness, or the "fill width" option of the view is set to the narrow setting.

## Wide window, Fill width view option
![screen shot 2018-04-25 at 4 55 55 pm](https://user-images.githubusercontent.com/624132/39275210-2690ecca-48aa-11e8-8687-242d03578581.png)

## Narrow window, Fill width view option
![screen shot 2018-04-25 at 4 57 31 pm](https://user-images.githubusercontent.com/624132/39275213-26b5e1a6-48aa-11e8-9e12-3b7573d97db0.png)

## Wide window, Narrow width view option
![screen shot 2018-04-25 at 4 57 19 pm](https://user-images.githubusercontent.com/624132/39275212-26a366ca-48aa-11e8-97cd-9bdba8297921.png)

**Comment by benubois** [comment]
Hi @dotHTM,

Thanks for reporting this, and for all the detailed screenshots!

Should be fixed now.
