### ISSUE TITLE
Discovery (`rel=alternate`) for JSON feeds?

### ISSUE THREAD

**Issue by croaky** [feedbin/feedbin#250]
When adding a blog URL (not its feed URL) in the Feedbin UI 
such as https://example.org, which contains this HTML...

```html
<link rel="alternate" href="https://example.org/feed.json" type="application/json" />
```

...it appears that Feedbin does not discover the JSON feed. According to the "Discovery" section of [the JSON feed spec](https://jsonfeed.org/version/1), that meta link should be valid?

I'm wondering if one these approaches might help?

* add `"application/json"` to `type` in `app/models/source/meta_links.rb`?
* look for canonical route `/feed.json` if the given domain is a root route?

One edge case that should probably also be supported(?) b/c of the [link spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) is relative URLs:

```html
<link rel="alternate" href="feed.json" type="application/json" />
```

^ I've tested this on a live site at Feedly and it works there.

**Comment by maracuja-juice** [comment]
Hmm with the blogs I've added so far it works fine. I think a specific example would be helpful here.

**Comment by croaky** [comment]
I was testing with https://www.statusok.com/

**Comment by endquote** [comment]
I'm running into this too.

https://endquote.com/

`<link rel="alternate" name="Josh Santangelo" type="application/json" href="https://endquote.com/api/feed">`

Entering endquote.com into the Feedbin subscribe box doesn't find the feed. If I add the full feed URL, it works ok.

**Comment by croaky** [comment]
Thanks, @benubois!
