### ISSUE TITLE
Origin of LazyLoadFilter

### ISSUE THREAD

**Issue by rachel-sharp** [feedbin/feedbin#251]
In the ContentFormatter, one of the steps in the HTML Pipeline is the LazyLoadFilter - I searched in the html-pipeline project, all of Feedbin's projects and did a google search, but wasn't able to find anything.  Does anyone know where this might be defined?

**Comment by benubois** [comment]
Hi @rachel-sharp,

Feedbin uses a [forked version of html-pipeline](https://github.com/feedbin/html-pipeline/blob/feedbin/lib/html/pipeline/lazy_load_filter.rb) that defines a few extra filters.

Thanks!
