### ISSUE TITLE
Please enhance search

### ISSUE THREAD

**Issue by molstrangler** [feedbin/feedbin#254]
Hi,

Can you please improve the search feature in FeedBin.

* Search a specific feed
* Search a specific tag
* Allow some AND, OR logic
* Allow "" for grouping words

**Comment by benubois** [comment]
All of these things are already possible! [See the documentation](https://feedbin.com/help/search-syntax/) for examples.

**Comment by molstrangler** [comment]
It would be nice to have a pop-up box when clicking the magnifying glass icon.  I don't search that often and remembering all these options will be a real pain, having to refer the docs all the time.

Search Text:
Search for a complete phrase: `[tick box]`
Search stared messaged only: `[tick box]`
Search for: `[Read; Unread]`
Search in only:`[Content; Author; Title ]`
Search in the feed: `[drop menu listing all feeds]`
Search in the tag: `[drop menu listing all tags]`
