### ISSUE TITLE
Suggestion: Use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [feedbin/feedbin#264]
Would you be up for using [Dependabot](https://dependabot.com) to automatically create PRs for dependency updates? I built it, and now have a couple of thousand people using it - was hoping it might save you a little time, and it's totally free for open source.

I'm particularly keen to get well-tested open source repos like this one using it because it aggregates the results of everyone's test runs when updating a dependency, and will soon use that data to report back any bugs to dependency maintainers. Would be rad to have feedbin as one of the test suites maintainers would be able to see their new version is working with/failing on.

**Comment by benubois** [comment]
Hi @greysteil,

Thanks for the suggestion! Dependabot is a great idea and very well done.

Giving it a try.

**Comment by greysteil** [comment]
Awesome! I'll try and help out with some of the PRs, and just ping me if it does anything you don't like 🙂
