### ISSUE TITLE
Article from jwz.org is borked

### ISSUE THREAD

**Issue by OllyHodgson** [feedbin/feedbin#281]
https://www.jwz.org/blog/2018/09/trump-is-under-spiritual-attack-from-luciferian-advanced-beings-who-control-the-world/ (from https://www.jwz.org/blog/feed/) doesn't render quite correctly.

The HTML is "interesting", which may complicate things. But the embedded video box sits on top of the blockquote that follows it.

![image](https://user-images.githubusercontent.com/437224/45437405-a396cf80-b6ac-11e8-8636-05aa53227158.png)

**Comment by benubois** [comment]
Thanks! Should be fixed now.
