### ISSUE TITLE
More granular controls for "actions", eg "by:" field

### ISSUE THREAD

**Issue by Trevortds** [feedbin/feedbin#282]
Use case: 
I subscribe to the washington post world news feed, which contains a lot of posts from Associated Press. A LOT. I don't particularly want to see them, because they're so simple, often just the existence of an event with a one-sentence description. Trouble is, "Associated Press" is a pretty common search term in regular hand-written high-quality articles as well, as one source among many. It would be helpful to be able to filter on by-line rather than a full-text search. 

I'm sure other applications for this exist that I can't think of at the moment.

**Comment by benubois** [comment]
Hi @Trevortds,

If I'm understanding correctly, you should be able to do this now.

Try using the search: `author:"Associated Press"`

You can also search the fields `title` and `content`.

The full Action would look like this:

![feedbin com_settings_actions_new](https://user-images.githubusercontent.com/133809/46426578-d5bbb000-c6f3-11e8-9b6d-4383a871ab21.png)

![feedbin com_settings_actions_new 1](https://user-images.githubusercontent.com/133809/46426563-ca688480-c6f3-11e8-93f4-17efc0d92a04.png)

**Comment by Trevortds** [comment]
Is the query language documented somewhere?
