### ISSUE TITLE
Difference-finding algorithm is too lax

### ISSUE THREAD

**Issue by bdesham** [feedbin/feedbin#287]
I appreciate that finding and displaying the differences between two pieces of unstructured text is a difficult job. But I think the algorithm Feedbin is using for its “viewing changes since original” feature has too low of a threshold for deciding that two pieces of text are different versions of each other:

![Screenshot of Feedbin showing an updated part of an article.](https://user-images.githubusercontent.com/354230/47815070-8c6b7a00-dd0c-11e8-84c7-a1a878174f75.png)

Here Feedbin is trying to show the differences between the last &lt;p&gt; of the original article and the last &lt;blockquote&gt; of the newest version. The only elements these two passages have in common are a colon, the word “MacBook”, and a period. The original last paragraph was “Previously: Forthcoming MacBook and Mac mini Updates”.  In [the latest version of the article](https://mjtsai.com/blog/2018/10/30/october-2018-apple-event/), there is a paragraph that reads

> Previously: Forthcoming MacBook and Mac mini Updates, Mac Sales Down in Q3 2018 Amid a Lack of Updates.

This contains the same words in the same order as the original last paragraph—it should have been tagged as being the updated version of that original last paragraph. Is there any chance that some parameter could be tweaked to make “viewing changes” more useful? It’s a great feature, and one I use almost every day, but I think it needs refinement to be as useful as it could be.

(I’ll add that the passage “Forthcoming MacBook and Mac mini Updates” was and is a hyperlink, and I’m pretty sure the target of the link hasn’t changed. Is the diff algorithm throwing out HTML tags and looking just at the text content? Not doing so could certainly produce a lot of false-positive changes (when the author moves some tags around without actually changing the text), but maybe the algorithm could take the document structure into account instead of just looking at the text?)

**Comment by benubois** [comment]
I know what you mean and I'd like it to work better too. Feedbin relies on [some code I found in Discourse](https://github.com/discourse/discourse/blob/master/lib/onpdiff.rb) and how it works is over my head.

If you know of something that does a better job of this or have code to contribute I'm all ears.
