### ISSUE TITLE
Enhancement - add Dockerfile https://github.com/thomas-illiet/feedbin-docker

### ISSUE THREAD

**Issue by johndpope** [feedbin/feedbin#288]
https://github.com/thomas-illiet/feedbin-docker

**Comment by benubois** [comment]
I don't use and don't know Docker, and therefore I'm not qualified or interested in maintaining a Dockerfile. Having this as a separate project maintained by someone else is perfect.

Up for linking to it in an [install guide](https://github.com/feedbin/feedbin/tree/master/doc) if you want to submit a pr.

**Comment by johndpope** [comment]
fyi @thomas-illiet
