### ISSUE TITLE
Issue with duplicate articles in some feeds

### ISSUE THREAD

**Issue by czert** [feedbin/feedbin#297]
In my slashdot feed (http://rss.slashdot.org/Slashdot/slashdot), almost every article is duplicated one or more times, which is really annoying. It has been like that for a long time (years?), but i didn't used to happen.

Is there a way to fix this?

Example:
![2019-01-08-145720_317x943_scrot](https://user-images.githubusercontent.com/1013310/50835017-d6e52480-1355-11e9-8937-b4c3ef47c359.png)

**Comment by czert** [comment]
(This might be a related issue: #84)

**Comment by benubois** [comment]
Sorry for the trouble!

Looks like this feed does not use IDs which uniquely identify items. They are also changing item attributes (like the url) after publishing which makes it look like a different item.

Try subscribing to the atom feed, which does use IDs and does not have this problem: http://rss.slashdot.org/Slashdot/slashdotMainatom

**Comment by czert** [comment]
@benubois works great, thank you!
