### ISSUE TITLE
Feature Request: Actions - Filter by title starting with phrase or word

### ISSUE THREAD

**Issue by kmcginnes** [feedbin/feedbin#314]
## Story

As a subscription administrator
I want to filter feeds by title starting with a specific word or phrase
So that articles with that word or phrase in the middle or end are not filtered out

## Scenario

Many of the writers that I subscribe to promote their podcasts in their feeds. Also, some feeds have recurring article series that I'd like to filter out.

In both of these cases, there is typically a phrase that I can filter on at the very beginning of the title. However, the way the filtering works now, if that word or phrase is common enough then I could potentially filter out articles that I don't want to filter.

## Example of problem

**Feed**

```
http://feedpress.me/512pixels
```

**Filter**

```
title.exact:"Connected"
```

**Results**

```
- Connected #237: All the Different Flavors of iCloud
- Tickets for Connected Live at WWDC
- Connected #236: Rosencrantz Says
- ... many more following the same pattern as the first and third
```

**Comment by benubois** [comment]
Hi @kmcginnes,

I think the best way to achieve this would be with a wildcard. Something like this should work:

title.exact:(Connected #*:)
