### ISSUE TITLE
Is there any way to use self-host Mercury parser ?

### ISSUE THREAD

**Issue by jhangyu** [feedbin/feedbin#316]
Mercury Web Parser has been shut down and stop responding to requests on April 15, 2019.
But there are [other ways](https://github.com/HenryQW/mercury-parser-api) to build a self-hosted Mercury Web Parser API.

Is there any way to replace the deprecated Postlight Mercury Web Parser API to self-hosted web parser API?
I tried to change the EXTRACT_HOST variable is feedbin, but nothing happened.

Thanks!!

**Comment by Zegnat** [comment]
You can read about [the Mercury move on the Feedbin Blog](https://feedbin.com/blog/2019/03/11/the-future-of-full-content/). Feedbin uses [feedbin/extract](https://github.com/feedbin/extract) to create a web API around the open-sourced parser. This solution should be fully self-hostable, just like Feedbin itself.

Hope that helps!

**Comment by jhangyu** [comment]
Thank you for the respond! 
I'll try deploy feedbin/extract service to link with feedbin server.
Thanks!
