### ISSUE TITLE
Subscribe to Vimeo feed

### ISSUE THREAD

**Issue by equivalentideas** [feedbin/feedbin#318]
Unfortunately Vimeo don't seem to have RSS feeds :( But I'd love to keep up to date with video producers in FeedBin :)

**Comment by benubois** [comment]
Hi @equivalentideas,

Vimeo does actually provide two types of RSS feeds that I'm aware of:

User feeds:

```
https://vimeo.com/USER/videos
```

Channel feeds

```
https://vimeo.com/channels/CHANNEL/videos
```

You can subscribe to either of these types of URLs and Feedbin will find the feed url. You can also add `/rss` to either and view the RSS source directly.

Thanks!

Ben

**Comment by equivalentideas** [comment]
Amazing @benubois thanks :two_hearts:

**Comment by iyx** [comment]
User feed stopped providing a title for me, does anyone else has this problem?
