### ISSUE TITLE
View a feed's URL in the Edit pane

### ISSUE THREAD

**Issue by louh** [feedbin/feedbin#347]
Not sure if this is the best place to ask, but is there a way to view the original URL of a feed? I'm trying to disambiguate between two different feeds from a new source that were added at different times, have different content, but were labeled with the same name.

Thanks!

**Comment by Zegnat** [comment]
If you go to your subscriptions page (three dots in the top right, then Subscriptions) you should see all the feeds you are subscribed to. You can then filter by name and look at see the feed URLs right below the name.

<img width="1235" alt="Screenshot: showing duplicate mathowie feeds, same name, different URLs" src="https://user-images.githubusercontent.com/490579/64327827-a466f680-cfcc-11e9-8a46-4abbe990c8f7.png">

**Comment by louh** [comment]
Yep, that did the trick. Thanks!
