### ISSUE TITLE
Appearance settings per client

### ISSUE THREAD

**Issue by endquote** [feedbin/feedbin#370]
I'm trying out the Feedbin app on the desktop and mobile, but would like different display settings (dark/light, font size) depending on the device I'm using.

**Comment by endquote** [comment]
A partial workaround for this is to set the mobile client to whatever you like, and then use userstyles in a wrapper like Fluid on desktop.

You can't apply a class to the `<body>` to set an overall light/dark style this way, though.

**Comment by angristan** [comment]
This seems to have been implemented! https://feedbin.com/blog/2020/02/03/automatic-dark-mode-and-more/
