### ISSUE TITLE
Missing <video> tag attributes

### ISSUE THREAD

**Issue by endquote** [feedbin/feedbin#371]
I have a custom feed with lots of `<video>` tags. Certain attributes of those seem to be stripped in the Feedbin client: `playsinline`, `autoplay`, `loop`, and `muted`. 

This is probably similar to #157, which I think was fixed.

Here is an example feed, also pasted below: http://laundry.endquote.com/test.xml

```xml
<?xml version="1.0" encoding="UTF-8"?><rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
    <channel>
        <title><![CDATA[instagram-timeline]]></title>
        <description><![CDATA[instagram-timeline]]></description>
        <link>http://github.com/endquote/laundry</link>
        <generator>Laundry</generator>
        <lastBuildDate>Thu, 02 Jan 2020 09:01:48 GMT</lastBuildDate>
        <atom:link href="http://github.com/endquote/laundry" rel="self" type="application/rss+xml"/>
        <item>
            <title><![CDATA[zach.lieberman: Blobbing out 2019…]]></title>
            <description><![CDATA[<p><video controls src="https://laundry.endquote.com/jobs/instagram-timeline/items/instagram/media/2211384917136058359_2371157357.mp4" poster="https://laundry.endquote.com/jobs/instagram-timeline/items/instagram/media/2211384917136058359_2371157357.jpg" width="720" height="720" playsinline autoplay loop muted></video></p><p>Blobbing out 2019 <a href="https://instagram.com/explore/tags/openframeworks/">#openframeworks</a></p><p>488 likes<p>5 comments</p>]]></description>
            <link>https://www.instagram.com/p/B6wat2fjSf3/</link>
            <guid isPermaLink="true">https://www.instagram.com/p/B6wat2fjSf3/</guid>
            <category><![CDATA[openframeworks]]></category>
            <dc:creator><![CDATA[zach.lieberman]]></dc:creator>
            <pubDate>Wed, 01 Jan 2020 00:14:21 GMT</pubDate>
        </item>
    </channel>
</rss>
```

[media.zip](https://github.com/feedbin/feedbin/files/4016647/media.zip)

**Comment by benubois** [comment]
Hi @endquote,

Thanks for reporting this!

`playsinline`, `loop`, and `muted` have been whitelisted. However, I've left off `autoplay` for now as I feel this would be surprising behavior.

**Comment by endquote** [comment]
Thanks! I see the attributes now.

`loop` seems to be working correctly.

Something's up with `playsinline`. Videos still go full-screen on iOS in the Feedbin client (which has custom media controls), but no longer do so in Reeder (which is just rendering the default OS controls). I see a bunch of fullscreen stuff [in here](https://github.com/feedbin/feedbin/blob/5a2afe2be190a333de90b1277af464b3b1f2cfb5/vendor/assets/javascripts/mediaelement-and-player.js#L1158), maybe there's some setting to be passed to that component?

`muted` also seems to work correctly, but the custom controls don't provide a way to unmute. But as long as the video goes fullscreen, there's an unmute control there.

Agreed on leaving out `autoplay`. I don't actually use it in my feed, but just wanted to note that it could show up.
