### ISSUE TITLE
Promoting user to admin status

### ISSUE THREAD

**Issue by angristan** [feedbin/feedbin#398]
Hello,

As far as I can tell from the source code there is no way to make a user an admin.

From my understanding an admin has these capabilities:

- Delete users through the admin page
- Access sidekiq trough `/sidekiq`

I ended up doing this:

```sql
UPDATE users SET admin=true WHERE id=1
```

This should be a least documented. A good way to handle admins would be to add a rake task, maybe? If you agree I could make a PR.

**Comment by benubois** [comment]
A rake task for this sounds good.

It would be more rails-like to do it like this:

```ruby
User.find(1).update(admin: true)
```

**Comment by angristan** [comment]
Thanks! I made a PR.
