### ISSUE TITLE
Share to Feedbin pages

### ISSUE THREAD

**Issue by endquote** [feedbin/feedbin#432]
I like using the Feedbin Pages feature, and would like to make it even easier, by sending articles in other Feedbin feeds into Pages.

The [Share & Save](https://feedbin.com/settings/sharing) page doesn't include Pages, and it's not documented as a [Read-it-later Service](https://feedbin.com/help/sharing-read-it-later-services/). I'm guessing it can't be added there since [the API wants a POST](https://github.com/feedbin/feedbin-api/blob/master/content/pages.md) rather than a GET.

It would be nice if:
* you could add a Page with a GET
* Pages was included by default in the sharing services
* The new API was listed on the read-it-later page for use in other ways
* The "[Send to Feedbin](https://feedbin.com/settings/newsletters_pages)" bookmarklet could use this API too, just for consistency

**Comment by benubois** [comment]
Hi @endquote,

Pages exists for the purpose of getting one-off articles from the web into Feedbin. So I feel it would be redundant to send stuff from Feedbin into pages.

There is another possible feature like a true "read later" queue that would be more appropriate for what you describe.
