### ISSUE TITLE
Hyperlinks within inserted text are not underlined

### ISSUE THREAD

**Issue by bdesham** [feedbin/feedbin#439]
One of my favorite features of Feedbin is that it not only calls out which articles have been updated, but actually shows you which pieces of text are different from those in the original article.

I’ve noticed that if a post is modified to include a hyperlink, and you have “view changes since original” turned on, the hyperlink is not underlined and so you can’t tell which pieces of text are hyperlinks. (At least not without mousing over them.) This happens for me in Firefox 74 and Chrome 80 on macOS. Here’s an example from Daring Fireball:

<img width="1297" alt="Screen Shot 2020-03-31 at 10 49 15 AM" src="https://user-images.githubusercontent.com/354230/78060635-b8938c00-7340-11ea-9f34-fb7f28630f45.png">

You can see in [the original article](https://daringfireball.net/2020/03/regarding_zoom) that there are three hyperlinks in this paragraph. I’d like to request that hyperlinks in these green “inserted” sections get the usual underline styling.

As a workaround, I’ve used the [Stylus browser extension](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) to apply this custom style to Feedbin pages:

``` css
.inline-diff ins a,
.inline-diff .diff-ins a,
a.diff-ins ins {
    text-decoration: underline;
}
```

(This may or may not be helpful for you 🙂)

**Comment by benubois** [comment]
Good find, thank you!

**Comment by bdesham** [comment]
Looks great! Thank you ❤️
