### ISSUE TITLE
Unread/All doesn't respect sort order

### ISSUE THREAD

**Issue by endquote** [feedbin/feedbin#440]
I have the "Unread Sort" preference set to "oldest first".

When the top-left dropdown is set to "unread", I see unread posts in order from oldest to newest, as it should.

When I switch it to "all", it the sort is changed from newest to oldest.

**Comment by benubois** [comment]
The _Unread_ in "Unread Sort" means that this setting applies to the unread view only.

The reason for this if you were to sort from oldest to newest on the _All_ view, you would have to scroll through potentially tens of thousands of items to actually get to anything new.

Maybe you could explain why this would be useful for you?

**Comment by endquote** [comment]
Oh, right. That makes sense!
