### ISSUE TITLE
Unable to subscribe to feed

### ISSUE THREAD

**Issue by FredericJacobs** [feedbin/feedbin#544]
When I try with other RSS clients, subscribing to the following works just fine: https://www.airbus.com/rss-feeds/all-pr-news-stories.rss

But with Feedbin, it's failing for some reason.

**Comment by benubois** [comment]
Hi @FredericJacobs,

I noticed one weird thing with this feed is that it's sending its content as gzip encoded even when `Accept-Encoding: gzip` is omitted.

That's possible to work around.

The other issue is that the [parser Feedbin uses](https://github.com/feedjira/feedjira) seems to have a problem with the feed's UTF-16 encoding. I'll have to dig into it a bit more to see what is going on. It is usually able to handle a variety of encodings.

**Comment by FredericJacobs** [comment]
Thanks for the feedback. I was surprised it worked in other clients but not Feedbin.

**Comment by benubois** [comment]
This should be fixed now. Thanks!

**Comment by FredericJacobs** [comment]
Verified fixed, thanks!
