### ISSUE TITLE
Display videos in tweets

### ISSUE THREAD

**Issue by metmarkosaric** [feedbin/feedbin#554]
I use Feedbin to read my Twitter feed and it's a great experience. There's an increasing number of tweets that feature videos and they don't seem to work in Feedbin. I'm using Firefox and I get error message saying "no video with supported format and MIME type found". If I click on the tweet and view it on Twitter, then the video works fine. Would be great if it's possible to view Twitter videos directly in Feedbin too. Thanks!

**Comment by benubois** [comment]
Could you provide an example?

**Comment by metmarkosaric** [comment]
Sure. Here's a tweet from Firefox with a video in it: https://twitter.com/firefox/status/1313962304602423296

And here's how it looks in Feedbin:

![Screenshot from 2020-10-11 18-09-06](https://user-images.githubusercontent.com/34340819/95683665-fd03bc80-0bec-11eb-87eb-0a11b0a41b26.png)

**Comment by benubois** [comment]
Looks fine to me in Firefox. What OS is this? Maybe you need a plugin to play mp4 files?

<img width="1518" alt="Screen Shot 2020-10-11 at 6 32 54 PM" src="https://user-images.githubusercontent.com/133809/95684204-3e499b80-0bf0-11eb-8e92-7accefd1a317.png">

**Comment by metmarkosaric** [comment]
Ignore this. Seems like Firefox was blocking it with the Enhanced Tracking Protection on despite it not being an ad/tracker. Thanks!
