### ISSUE TITLE
Empty `<img>` tag generated for certain images in feed content

### ISSUE THREAD

**Issue by johnbillion** [feedbin/feedbin#601]
I've been noticing for a while that Feedbin doesn't show any images from within content from [wptavern.com/feed](https://wptavern.com/feed). The images display correctly when viewing a blog post at its URL, the HTML markup is valid, and the images render okay in other feed services such as Feedly.

Feedbin renders an empty `<img>` tag, followed by the text from the `<figcaption>` provided in the feed.

Several examples can be seen in [this article](https://wptavern.com/wp-lookout-lets-wordpress-users-track-and-receive-notifications-for-their-preferred-plugins-and-themes). There is a "How the Service Works" heading that's followed by an image. This does not render in Feedbin.

The source HTML for the image is this:

```html
<figure class="wp-block-image alignwide size-full">
    <img data-attachment-id="111190" data-permalink="https://wptavern.com/wp-lookout-lets-wordpress-users-track-and-receive-notifications-for-their-preferred-plugins-and-themes/wp-lookout-recent-activity" data-orig-file="https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity.jpg" data-orig-size="1792,1124" data-comments-opened="0" data-image-meta='{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}' data-image-title="wp-lookout-recent-activity" data-image-description="" data-medium-file="https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity-300x188.jpg" data-large-file="https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity-500x314.jpg" loading="lazy" width="1792" height="1124" src="https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity.jpg" alt="Single plugin tracking history via the WP Lookout website." class="wp-image-111190" srcset="https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity.jpg 1792w, https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity-300x188.jpg 300w, https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity-500x314.jpg 500w, https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity-768x482.jpg 768w, https://wptavern.com/wp-content/uploads/2021/01/wp-lookout-recent-activity-1536x963.jpg 1536w" sizes="(max-width: 1792px) 100vw, 1792px">
    <figcaption>Single plugin tracking history.</figcaption>
</figure>
```

Not sure if this relates to the markup (there are a lot of attributes on the `img`) or the Feedbin image proxy service, or something else.

**Comment by benubois** [comment]
Hi @johnbillion,

Sorry for the trouble!

Unfortunately I'm not able to reproduce this issue. Here's what I see for that example.

<img width="1701" alt="Screen Shot 2021-01-28 at 10 13 06 PM" src="https://user-images.githubusercontent.com/133809/106238692-2b1a0600-61b6-11eb-88fb-42bbdcf6a4be.png">

Is it possible an extension is interfering? What browser is this in?

**Comment by johnbillion** [comment]
I'm using Brave 88 on macOS 10.15.6, however the Brave Shields are disabled for feedbin.com. I just tested this in Chrome and Firefox with no extensions, and the issue persists in those browsers too. I've not noticed issues with images in any of my other feeds.

In the console I have one 404 error showing, but I don't know where it's triggered.

```
Failed to load resource: the server responded with a status of 404 ()
https://camo.feedbinusercontent.com/b1db29469483eed77ef926193d59044cba9a6189/68747470733a2f2f7062732e7477696d672e636f6d2f70726f66696c655f696d616765732f313231343438353237393234303739343131342f653950446d426d305f6269676765722e6a7067
```

**Comment by johnbillion** [comment]
Screenshot:

<img width="329" alt="" src="https://user-images.githubusercontent.com/208434/106270528-6ce69300-622e-11eb-8d52-e90b5a90b308.png">

**Comment by benubois** [comment]
Just to be certain we're looking at the same thing, could you right click on the summary to copy and paste the link to the article?

<img width="574" alt="Screen Shot 2021-01-29 at 1 30 17 PM" src="https://user-images.githubusercontent.com/133809/106329561-84297e80-6236-11eb-9233-8f8ffb24cff4.png">

The same input into Feedbin's sanitization should produce the same output so that's the only other thing I can think of.

**Comment by johnbillion** [comment]
Yep that's the one. https://wptavern.com/wp-lookout-lets-wordpress-users-track-and-receive-notifications-for-their-preferred-plugins-and-themes?utm_source=rss&utm_medium=rss&utm_campaign=wp-lookout-lets-wordpress-users-track-and-receive-notifications-for-their-preferred-plugins-and-themes

**Comment by johnbillion** [comment]
I just checked the entry in the Readably app on Android, same outcome.

Screenshot:

![Screenshot_20210129-234240_Readably](https://user-images.githubusercontent.com/208434/106334863-d779ec00-628b-11eb-9f9b-b52e6994132c.jpg)

**Comment by johnbillion** [comment]
I just manually queried the Feedbin API and I'm seeing the same problem there. The item `id` is `2865599624` and the `feed_id` is `16374`.

```
<h2>How the Service Works</h2>\n\n\n\n<img>Single plugin tracking history.
```

**Comment by benubois** [comment]
Sorry, I meant the link to the article in Feedbin. It should look something like `https://feedbin.com/entries/12345`

**Comment by benubois** [comment]
Ignore that. I see you're latest comment has the ID. Thanks!

**Comment by benubois** [comment]
Ah, It looks like you're actually subscribed to `http://planet.wordpress.org/feed/` which is republishing posts from WP Tavern. The original XML source does not contain the images:

```xml
&lt;h2&gt;How the Service Works&lt;/h2&gt;

&lt;img /&gt;Single plugin tracking history.
```

**Comment by johnbillion** [comment]
Oh you're absolutely right, I am! Thanks. Sorry for the noise. Keep up the good work with Feedbin, I'm a fan.
