### ISSUE TITLE
Link popover menu breaks in Firefox when link contents split over two lines

### ISSUE THREAD

**Issue by CAYdenberg** [feedbin/feedbin#606]
1. Using Firefox, open an article within Feedbin that contains in-article links.
2. Hover over a link that splits across two lines.
3. appears at the left margin of the text body, top-aligned with the start of the hovered anchor tag. (This is different I believe from the desired behaviour in Chrome where the menu button appears at the right of the anchor tag.)
4. Click on that button - it briefly changes position and then disappears.

**Comment by benubois** [comment]
Happy to look into this. Could you provide the feed url and article I should look at that exhibits this problem?

**Comment by CAYdenberg** [comment]
Screenshot below. The article is https://fivethirtyeight.com/features/our-guide-to-super-bowl-lv/ and the Feed URL is https://fivethirtyeight.com/features/feed/.

To reproduce, the key is that the width of the viewport and/or the frame needs to be adjusted so that the link breaks across multiple lines, otherwise you won't see it happen. I suspect absolute positioning is used to place the popover and that the rules work somewhat different in Firefox.

![image](https://user-images.githubusercontent.com/3757136/106845557-06afa500-6660-11eb-92e0-6a43d2efa752.png)
