### ISSUE TITLE
Include “Show Retweets” toggle when subscribing to Twitter accounts

### ISSUE THREAD

**Issue by rybesh** [feedbin/feedbin#636]
Currently when subscribing to Twitter accounts, one has the option to turn on/off the “Media Only” toggle. But to access the “Show Retweets” toggle, one has to subscribe to the account, then find the subscription in the subscription list, and turn off “Show Retweets” there. (AFAIK this is not even possible using the Feedbin iOS app.) It would be much more convenient to access the toggle when subscribing, similar to the “Media Only” toggle. (When Twitter subscriptions were first introduced to Feedbin, it was possible to turn off retweets when subscribing, but then it changed for some reason.)

Alternatively, it would be great to be able to set “Show Retweets” as off by default for all new Twitter subscriptions.

**Comment by benubois** [comment]
Hi @rybesh,

A global retweet filter is achievable using [Actions](https://feedbin.com/settings/actions).

Make your search term `twitter_retweet:true` and apply it to all feeds.

Thanks!

<img width="1279" alt="Screenshot 2021-04-01 at 08 53 35" src="https://user-images.githubusercontent.com/133809/113320839-d420d200-92c7-11eb-8b4a-e49153907eb2.png">

**Comment by rybesh** [comment]
Thanks! 🙏
