### ISSUE TITLE
Subscribing to Youtube feed fails

### ISSUE THREAD

**Issue by ttepasse** [feedbin/feedbin#643]
I tried subscribing to the Youtube channel https://www.youtube.com/c/JustWrite and it didn't work: _„No feed found“_.

The I dig into the Youtube source code and found URLs for a canonical Youtube Channel ID and constructed a Youtube Feed URL: https://www.youtube.com/feeds/videos.xml?channel_id=UCx0L2ZdYfiq-tsAXb8IXpQg

Curling that URL found an Atom feed and while the W3C‘s feed validator finds missing date elements the feed is otherwise well-formed. But then it get's mysterious. Putting that feed URL directly into Feedbin‘s Add sheet still gives the error message _„No feed found“_. Huh?

**Comment by benubois** [comment]
Hi @ttepasse,

Sorry for the trouble. YouTube is periodically blocking Feedbin. My guess is it's a new rate-limit. Unfortunately there is no information or communication from YouTube on what exactly the rate limit is. 

It's working again at the moment and for the future I'm planning on reducing how often Feedbin checks YouTube feeds.
