### ISSUE TITLE
Use escape to close keyboard shortcuts modal

### ISSUE THREAD

**Issue by will-stone** [feedbin/feedbin#646]
Hi 👋 Feedbin newbie here. Really liking the product so far. Is this the correct place to post feature requests?

If so, it would be nice to be able to close the keyboard shortcuts cheatsheet modal using <kbd>escape</kbd> key. When I'm learning a new product, I instinctively now hit <kbd>shift+?</kbd> to see if there's a keyboard cheatsheet. However, not being able to close the modal using <kbd>escape</kbd> means having to jump back to the mouse.

I've got as far as finding [this line of code](https://github.com/feedbin/feedbin/blob/master/app/assets/javascripts/web/keyboard.js.coffee#L300) but alas, I'm no coffeescript expert.

**Comment by benubois** [comment]
Done. Thanks for the suggestion!

**Comment by will-stone** [comment]
Thanks 🙂
