### ISSUE TITLE
Migrating database without super user

### ISSUE THREAD

**Issue by ghost** [feedbin/feedbin#66]
I'm trying to deploy the app on heroku and in other areas where I could set myself as a super user, setting up the app was simple.  But apparently Heroku doesn't allow this, I have added the hstore extension but the migration always fails here:

```
class AddFeedIdToEntryStates < ActiveRecord::Migration
  def up
    add_column :entry_states, :feed_id, :integer
    add_index :entry_states, :feed_id

   EntryState.find_each do |entry_state|  <~ HERE
      entry_state.feed_id = entry_state.entry.feed_id
      entry_state.save!
    end
  end

  def down
    remove_column :entry_states, :feed_id
  end
end
```

Does anyone have any idea how to work around this issue?  it's eating my brain. lol

**Comment by luto** [comment]
I'm running into the same issue. Once feedbin is started, it tells me to migrate, since the db doesn't exist. When I execute the given command (`bin/rake db:migrate`) it fails like this.

**Comment by luto** [comment]
`db:seed` doesn't work either, since I've got pending migrations (D'oh!).
