### ISSUE TITLE
Inline image formatting interrupts text flow

### ISSUE THREAD

**Issue by AndrewKvalheim** [feedbin/feedbin#668]
This [international newsletter](https://weeklyosm.eu/archives/15515) uses small inline images to provide links to translations:

> <img src="https://user-images.githubusercontent.com/1844746/166298278-89cd7f3e-966f-4118-abe1-5c2d79a302bc.png" alt="screenshot of expected output" width="593" />

In Feedbin, the images are rendered as block elements, interrupting the flow of the text:

> <img src="https://user-images.githubusercontent.com/1844746/166298320-336eeb68-5e6d-4566-af14-063b347d9eea.png" alt="screenshot of actual output" width="593" />

**Comment by benubois** [comment]
Hi @AndrewKvalheim,

Happy to look at this, but could you send the url for this example?

You can get it by right clicking on the summary and copying the link. It should be something like `https://feedbin.com/entries/1234`

Thanks!

<img width="1219" alt="Screenshot 2022-05-03 at 12 46 58" src="https://user-images.githubusercontent.com/133809/166440611-ec2610be-ae27-42a2-b7c2-eb2b8cb6dd07.png">

**Comment by AndrewKvalheim** [comment]
https://feedbin.com/entries/3581069429, thanks.

**Comment by AndrewKvalheim** [comment]
Checking back in—I don’t know when it changed but Feedbin is now correctly leaving the images inline:

> <img src="https://github.com/feedbin/feedbin/assets/1844746/a41e0be8-8971-4781-9d0a-600b2ff15cce" alt="screenshot of actual output" width="620" />

Thanks!
