### ISSUE TITLE
No matches for prefix* wildcard in actions

### ISSUE THREAD

**Issue by agostonbarna** [feedbin/feedbin#673]
Hi,
The prefix* wildcard described here https://feedbin.com/help/search-syntax/ used to work for me in actions, but I recently noticed that it's not matching some articles that it should.
Let me give an example.
When I have the search query:
`title:(celebrat*)` that should match celebrate, celebrates and celebrating, but it has no matches:
![FD7FD84D-943C-4333-99ED-50DC59F784CC](https://user-images.githubusercontent.com/5561396/186116730-3121c3eb-0cc8-497f-8e0a-851a0d4b24b4.png)
But if I use the exact word without the wildcard `title:(celebrates)` it matches the word Celebrates:
![58ADFC3A-2B51-4FDD-B320-3177D47ED547](https://user-images.githubusercontent.com/5561396/186116736-1097eccf-e3d6-4676-8c42-5da656960da8.png)

This is the feed that I used for the example: https://feeds.macrumors.com/MacRumors-All

**Comment by benubois** [comment]
Hi,

Wildcard searches only work for the `*.exact` fields, so in your example you could use this query:

```
title.exact:(celebrat*)
```

Thanks!

**Comment by agostonbarna** [comment]
@benubois: oh, I see. Thanks for the info, I'll use it with that instead.

I see that the docs use `title.exact` in the example

> You could get more precise matches using a wildcard like title.exact:(upgrade #*).

but it doesn't sound like it can't be used with `title`. 

> Wildcard searches only work for the *.exact fields

So I think it would worth mentioning this in the docs to avoid future issues like this.

Thanks!
