### ISSUE TITLE
RSS Feed not found on https://val.packett.cool/

### ISSUE THREAD

**Issue by leejoramo-d51** [feedbin/feedbin#691]
Just read a blog post linked to from Hacker News and wanted to subscribe. Being that the author is an open source dev and proponent of  the open web I was a bit shocked that Feedbin did not find an RSS feed.

[https://val.packett.cool/blog/ergonice/](https://val.packett.cool/blog/ergonice/)

So I looked into the HTML and there is a feed linked to in the <head>

```html
<link rel="alternate feed" href="/feed.xml" type="application/atom+xml" title="Val Packett's Blog">
```

which looks ok to me, although maybe the `rel="alternative feed"` should not included the word "feed"?

**Comment by benubois** [comment]
Thank for reporting this @leejoramo-d51! 

Should be fixed now.
