### ISSUE TITLE
Twitter API changes

### ISSUE THREAD

**Issue by nbousfield** [feedbin/feedbin#694]
Given the elimination of the free Twitter API and the somewhat unclear billing structure, it seems like Twitter feed support will need to be reconsidered if not removed. Have there been any announcements from Feedbin? (I have looked but not seen anything). NetNewsWire has already [announced](https://nnw.ranchero.com/2023/02/02/twitter-integration-to.html) removal of Twitter feeds for their own syncing accounts.

**Comment by benubois** [comment]
Nothing to announce yet as Twitter has not provided any details. There will be an update when/if they do.
