### ISSUE TITLE
Open YouTube video in YouTube

### ISSUE THREAD

**Issue by nelsonov** [feedbin/feedbin#695]
When I tap on a YouTube video to open a video that I have previously sent to Feedbin, it plays in the Feedbin app.  This is not what I want.  If I click on the title, it takes me to Safari and plays the video there.  This is not what I want.  If I hold down on the YouTube logo at the top of the window in Safari, there is an option to open in YouTube.  When I do that, it takes me to the YouTube Home screen (or startup screen what whatever you call it), not to the video.  After an hour of frustration, I have not found any want to get a saved YouTube video to play in the YouTube app.

**Comment by benubois** [comment]
Hi Lee,

That’s how universal links work on iOS. 

If you turn on the “Open in Safari” option, the universal links system will have a chance to intervene sooner and you will get the behavior you desire. 

Thanks!

Ben
