### ISSUE TITLE
hagerty.com RSS feed gives error

### ISSUE THREAD

**Issue by hisaac** [feedbin/feedbin#697]
Hi there!

I'm trying to subscribe to the hagerty.com RSS feed, but Feedbin gives me an error saying "No feed found" whenever I try.

The URL for the feed is https://www.hagerty.com/media/feed/.

I downloaded the feed and headers and uploaded them to a gist here: https://gist.github.com/hisaac/31670b19fa8a093690a3b0d1f0a4932e

Any ideas why this might be failing?

**Comment by benubois** [comment]
Hello @hisaac!

For this feed I'm seeing:

```bash
SSL_connect returned=1 errno=0 peeraddr=204.80.64.4:443 state=error: unsafe legacy renegotiation disabled
```

Feedbin uses SSL 3 which has removed support for a number of long-insecure connection methods.

It may be possible to work around as I don't think top-notch SSL security is critical for crawling feeds.

**Comment by hisaac** [comment]
Well I'd certainly appreciate being able to subscribe to this feed, but definitely consider it a low priority request. Not sure how much work would be involved with working around that.

**Comment by hisaac** [comment]
Also, just for extra information, I see there are a few other feeds on the page, but none of them are working (presumably for the same reason):

- https://www.hagerty.com/media/comments/feed/
- https://hagerty.com/media/feed
- https://hagerty.com/media/rss

**Comment by hisaac** [comment]
Thank you for fixing this @benubois! How soon should I expect the change to go live on feedbin.com?

**Comment by benubois** [comment]
This should be working now. Thanks!

**Comment by hisaac** [comment]
Works like a charm! 🙏

<img width="513" alt="CleanShot 2023-06-24 at 11 29 32@2x" src="https://github.com/feedbin/feedbin/assets/923876/c4ed10a1-bb2b-42b7-b926-761fe7494be1">

**Comment by markcellus** [comment]
Glad its working now. I see @benubois deleted my comment. I left it because I also use these feeds and was wondering why it wasnt working.
