### ISSUE TITLE
Airshow missing podcast entries

### ISSUE THREAD

**Issue by rubengarciam** [feedbin/feedbin#703]
I wasn't sure if this should go here or feedbin/support.
After testing Airshow I've realised that some podcasts are missing items or its feed hasn't been updated for a while. It doesn't matter whether you are subscribed, bookmarked or just searching for the Podcast for the first time.

Adding a couple of screenshots to showcase some examples:
![IMG_9008](https://user-images.githubusercontent.com/2044827/231334519-ed05a29b-2c62-488b-af76-93a5be169e6e.PNG)
![IMG_9007](https://user-images.githubusercontent.com/2044827/231334546-bea0c3ad-73b6-4b73-8f6e-a5e879136350.PNG)
![IMG_9006](https://user-images.githubusercontent.com/2044827/231334552-0af0717a-00df-4de9-87b2-93a06c8d88b9.PNG)
![IMG_9005](https://user-images.githubusercontent.com/2044827/231334558-023b483d-a2da-4170-8a97-acad5db8d56f.PNG)

**Comment by benubois** [comment]
Hi @rubengarciam,

I think this can happen if a podcast is known to Airshow, but nobody subscribes to it so it ends up not being regularly refreshed.

I've made an update and it should ensure the latest data is returned even if this is the case.

Thanks!

Ben
