### ISSUE TITLE
Keyboard#selectNextUnreadFeed selects wrong feed

### ISSUE THREAD

**Issue by nanaya** [feedbin/feedbin#704]
Pressing spacebar on the last feed entry currently selects feed tag instead of the next feed in list.

From what I gather, this commit (https://github.com/feedbin/feedbin/commit/df9d891f46009bfa56e610ae3643953c346f870f#diff-b4f26b666e2ae17e995bbe8161eddd30c81f185f5076a1b3ee24d4cbf479b9beR335) which changes `.click` call in `clickItem` to use native function caused this bug: the original `click` targeted multiple elements with the last one being the one it actually ends up with (next feed) but the new one makes it always use the first element which is the tag instead of the next feed.

Reverting it to use jquery click would revert it to original behavior but I don't know what else might be impacted (and you probably don't want to do that anyway?)

![](https://s.myconan.tk/2023/04/firefox_2023-04-16_21-11-27.png)

**Comment by benubois** [comment]
Thanks @nanaya!

This commit introduced [searching within feeds](https://feedbin.com/blog/2023/02/08/search-upgrades/). The new feature uses Stimulus and it was necessary to switch from jQuery click events to JavaScript click events so Stimulus could listen for those.

Appreciate you taking the time to find this.

Ben
