### ISSUE TITLE
Feature Request: add alternative entry list view such as Title-Only 

### ISSUE THREAD

**Issue by jcrben** [feedbin/feedbin#710]
Feedly has a setting that you can apply on a per feed basis:
<img width="1194" alt="image" src="https://github.com/feedbin/feedbin/assets/5614134/82d98556-0aa7-4cd6-a8e4-ad97e67df177">

**Comment by benubois** [comment]
Hi @jcrben,

You can achieve a similar look by going to Format -> Advanced -> Inline.

<img width="2600" alt="Frame 1" src="https://github.com/feedbin/feedbin/assets/133809/d1b9faa9-dd44-4c27-96ab-cb5e530a66e9">
