### ISSUE TITLE
Better formatting for Substack newsletters

### ISSUE THREAD

**Issue by brendanlong** [feedbin/feedbin#718]
I'm not sure if you do this internally or if there's a library I should look at, but Substack emails are (for better or for worse) one of the main sources of newsletters now, and they get formatted pretty badly in Feedbin.

In rich text mode, they show with borders around the text, a duplicate title, and smaller-than-normal body text, and with rich text mode turned off, there's a huge gap between the subtitle and the duplicate title in the body, making it look like the article doesn't have any content.

Substack is common enough it seems worth figuring out their weird formatting to make these look nice.

For example: https://newsletters.feedbinusercontent.com/a7b/a7bcc2a48addf703a6393f1e93e5f411adad9a7d.html

Rich text on:
![Screenshot from 2024-02-19 21-56-53](https://github.com/feedbin/feedbin/assets/1447206/e33d57d6-adc2-4143-8b8e-3c607bf658b4)

Rich text off, at the top:
![Screenshot from 2024-02-19 21-56-46](https://github.com/feedbin/feedbin/assets/1447206/fa14a192-2800-4bad-bf0f-8ded8389fe03)

Rich text off, scrolled down:
![Screenshot from 2024-02-19 21-56-40](https://github.com/feedbin/feedbin/assets/1447206/7a1bae97-e457-4042-b890-e1f836404759)

**Comment by brendanlong** [comment]
Ideally it would look like this:

![fixed](https://github.com/feedbin/feedbin/assets/1447206/994da82b-d1b5-42fb-b69e-5a1be6a2a34e)

**Comment by benubois** [comment]
Hey @brendanlong!

I like your idea, but before anybody does work on it I wanted to check if you knew that there’s also RSS feeds available for substack publications?

Here’s how that looks for this one:

![Tuesday, 20 Feb 2024 08:43:04](https://github.com/feedbin/feedbin/assets/133809/02128edd-8b97-4500-baf8-257d85bf1c9f)

**Comment by brendanlong** [comment]
Yeah, unfortunately (last time I checked), Substack doesn't have subscriber RSS feeds, and the public feeds don't have full-text for subscriber-only articles. For example, most of <https://newsletter.pragmaticengineer.com/> is subscriber-only and the RSS feed looks like this:

<img width="1613" alt="Screenshot 2024-02-20 at 3 13 10 PM" src="https://github.com/feedbin/feedbin/assets/1447206/390ed99f-72f3-4587-af71-9f9144cd966f">

I think this is actually better than it used to be (looks like they show a much-longer preview) but I prefer to do my reading entirely in Feedbin.

**Comment by benubois** [comment]
Hi @brendanlong,

How about something like this? If you have any other tweaks for Substack newsletters they can be added to the new [Substack filter](https://github.com/feedbin/feedbin/blob/main/app/models/content_filters/substack.rb). 

This could break in the future since it relies on Substack continuing to identify the main content area of a newsletter with a `.body.markup` selector. However, I don't currently subscribe to any Substack newsletters, could you let me know if this happens?

![newsletter](https://github.com/feedbin/feedbin/assets/133809/4cf7ec7d-8a0c-461c-abbb-03abaa418477)
