### ISSUE TITLE
Psql Error while `rake db:setup`

### ISSUE THREAD

**Issue by enderahmetyurt** [feedbin/feedbin#732]
Hi,

I am getting `URI::InvalidURIError: the scheme postgres does not accept registry part: username:password@host:port (or bad hostname?) (URI::InvalidURIError)` error when I run `rake db:setup`

Running postgresql@14

should I do anything?

Regards.

![Screenshot 2024-09-26 at 17 00 08](https://github.com/user-attachments/assets/45e765ab-11f2-4ec0-8962-cc702366e94e)

**Comment by MatElGran** [comment]
The `DATABASE_URL` in `.env.example` (that you copied to `.env`) is only an example, the correct URL depends on your PostgreSQL setup and you have to change the value in this file accordingly.

**Comment by enderahmetyurt** [comment]
thank you. it's working now.
